# Site settings
title: Hyoeun Kim
email: khe9125@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: khe9125
github_username: hyoeunK

# Build settings
markdown: kramdown


#paginate: 4
#paginate_path: "blog/page:num"
